# py26,py31,py32 use an outdated version of Sphinx (<1.1)
# which doesn't include the texinfo builder.

language: python
before_install:
  - sudo apt-get -qq install texinfo
  - pip install -r requirements.txt
script: make PYTHON_VERSION="$PYTHON_VERSION" python.info
env:
  - PYTHON_VERSION="2.7"
  - PYTHON_VERSION="3.3"
  - PYTHON_VERSION="3.4"
deploy:
  provider: releases
  api_key:
    secure: UYiDGXXD4qFN2eXqI2mm290Oqj2DtN56meW1dYJ/nHKf6mdIV03lG24m6cvUjty/EOVjozSDTJVImzmnnPfC9r8KCHuCt8cylXeBRJLXx2IoeTXstVNZ2IBr9814DBxQUuGC83TTKHbWf/4lnJUuCPyri2T2u/ldV46ojHrPgGY=
  file: "python-${PYTHON_VERSION}.info"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
