# py26,py31,py32 use an outdated version of Sphinx (<1.1)
# which doesn't include the texinfo builder.

language: python
before_install:
  - sudo apt-get -qq install texinfo
  - pip install -r requirements.txt
script: make PYTHON_VERSION="$PYTHON_VERSION" python.info
env:
  - PYTHON_VERSION="2.7"
  - PYTHON_VERSION="3.3"
  - PYTHON_VERSION="3.4"
